/* clang-format off */
/* *INDENT-OFF* */
typedef enum {
	NUL		= '\0',		/* null character */
	SOH		= '\x01',	/* start of heading */
	STX		= '\x02',	/* start of text */
	ETX		= '\x03',	/* end of text */
	EOT		= '\x04',	/* end of transmission */
	ENQ		= '\x05',	/* enquiry */
	ACK		= '\x06',	/* acknowledge */
	BEL		= '\a',		/* bell */
	BS		= '\b',		/* backspace */
	HT		= '\t',		/* horizontal tab */
	LF		= '\n',		/* new line */
	VT		= '\v',		/* vertical tab */
	FF		= '\f',		/* form feed */
	CR		= '\r',		/* carriage ret */
	SO		= '\x0e',	/* shift out */
	SI		= '\x0f',	/* shift in */
	DLE		= '\x10',	/* data link escape */
	DC1		= '\x11',	/* device control 1 */
	DC2		= '\x12',	/* device control 2 */
	DC3		= '\x13',	/* device control 3 */
	DC4		= '\x14',	/* device control 4 */
	NAK		= '\x15',	/* negative ack. */
	SYN		= '\x16',	/* synchronous idle */
	ETB		= '\x17',	/* end of trans. blk */
	CAN		= '\x18',	/* cancel */
	EM		= '\x19',	/* end of medium */
	SUB		= '\x1a',	/* substitute */
	ESC		= '\x1b',	/* escape */
	FS		= '\x1c',	/* file separator */
	GS		= '\x1d',	/* group separator */
	RS		= '\x1e',	/* record separator */
	US		= '\x1f',	/* unit separator */
	SPACE		= ' ',
	EXCLAM		= '!',
	DQUOTE		= '"',
	HASH		= '#',
	DOLLAR		= '$',
	PERCENT		= '%',
	AMPERSAND	= '&',
	SQUOTE		= '\'',
	LPAREN		= '(',
	RPAREN		= ')',
	STAR		= '*',
	PLUS		= '+',
	COMMA		= ',',
	MINUS		= '-',
	DOT		= '.',
	SLASH		= '/',

	ZERO		= '0',
	ONE		= '1',
	TWO		= '2',
	THREE		= '3',
	FOUR		= '4',
	FIVE		= '5',
	SIX		= '6',
	SEVEN		= '7',
	HEIGHT		= '8',
	NINE		= '9',

	COLON		= ':',
	SEMICOLON	= ';',
	LT		= '<',
	EQUAL		= '=',
	GT		= '>',
	QUESTION	= '?',
	ATSIGN		= '@',

	UCASE_A		= 'A',
	UCASE_B		= 'B',
	UCASE_C		= 'C',
	UCASE_D		= 'D',
	UCASE_E		= 'E',
	UCASE_F		= 'F',
	UCASE_G		= 'G',
	UCASE_H		= 'H',
	UCASE_I		= 'I',
	UCASE_J		= 'J',
	UCASE_K		= 'K',
	UCASE_L		= 'L',
	UCASE_M		= 'M',
	UCASE_N		= 'N',
	UCASE_O		= 'O',
	UCASE_P		= 'P',
	UCASE_Q		= 'Q',
	UCASE_R		= 'R',
	UCASE_S		= 'S',
	UCASE_T		= 'T',
	UCASE_U		= 'U',
	UCASE_V		= 'V',
	UCASE_W		= 'W',
	UCASE_X		= 'X',
	UCASE_Y		= 'Y',
	UCASE_Z		= 'Z',

	LBRACKET	= '[',
	BACKSLASH	= '\\',
	RBRACKET	= ']',
	XOR		= '^',
	UNDERSCORE	= '_',
	BACKTICK	= '`',

	LCASE_A		= 'a',
	LCASE_B		= 'b',
	LCASE_C		= 'c',
	LCASE_D		= 'd',
	LCASE_E		= 'e',
	LCASE_F		= 'f',
	LCASE_G		= 'g',
	LCASE_H		= 'h',
	LCASE_I		= 'i',
	LCASE_J		= 'j',
	LCASE_K		= 'k',
	LCASE_L		= 'l',
	LCASE_M		= 'm',
	LCASE_N		= 'n',
	LCASE_O		= 'o',
	LCASE_P		= 'p',
	LCASE_Q		= 'q',
	LCASE_R		= 'r',
	LCASE_S		= 's',
	LCASE_T		= 't',
	LCASE_U		= 'u',
	LCASE_V		= 'v',
	LCASE_W		= 'w',
	LCASE_X		= 'x',
	LCASE_Y		= 'y',
	LCASE_Z		= 'z',

	LBRACE		= '{',
	PIPE		= '|',
	RBRACE		= '}',
	TILDE		= '~',
	DEL		= '\x7f',

	/* iso_8859-1 */
	NBSP		= '\xa0',	/* NO-BREAK SPACE */
	IEXCLAM		= '\xa1',	/* INVERTED EXCLAMATION MARK */
	CENT		= '\xa2',	/* CENT SIGN */
	POUND		= '\xa3',	/* POUND SIGN */
	CURRENCY	= '\xa4',	/* CURRENCY SIGN */
	YEN		= '\xa5',	/* YEN SIGN */
	BROKEN_BAR	= '\xa6',	/* BROKEN BAR */
	SECTION		= '\xa7',	/* SECTION SIGN */
	DIAERESIS	= '\xa8',	/* DIAERESIS */
	COPYRIGHT	= '\xa9',	/* COPYRIGHT SIGN */
	FEMININE	= '\xaa',	/* FEMININE ORDINAL INDICATOR */
	LPANGLE		= '\xab',	/* LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
	NOT_SIGN	= '\xac',	/* NOT SIGN */
	SOFT_HYPHEN	= '\xad',	/* SOFT HYPHEN */
	REGISTERED	= '\xae',	/* REGISTERED SIGN */
	MACRON		= '\xaf',	/* MACRON */
	DEGREE		= '\xb0',	/* DEGREE SIGN */
	PLUS_MINUS	= '\xb1',	/* PLUS-MINUS SIGN */
	SUPER_TWO	= '\xb2',	/* SUPERSCRIPT TWO */
	SUPER_THREE	= '\xb3',	/* SUPERSCRIPT THREE */
	ACUTE		= '\xb4',	/* ACUTE ACCENT */
	MICRO		= '\xb5',	/* MICRO SIGN */
	PILCROW		= '\xb6',	/* PILCROW SIGN */
	MIDDLE_DOT	= '\xb7',	/* MIDDLE DOT */
	CEDILLA		= '\xb8',	/* CEDILLA */
	SUPER_ONE	= '\xb9',	/* SUPERSCRIPT ONE */
	MASCULINE	= '\xba',	/* MASCULINE ORDINAL INDICATOR */
	RPANGLE		= '\xbb',	/* RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
	FRAC_14		= '\xbc',	/* VULGAR FRACTION ONE QUARTER */
	FRAC_12		= '\xbd',	/* VULGAR FRACTION ONE HALF */
	FRAC_34		= '\xbe',	/* VULGAR FRACTION THREE QUARTERS */
	IQUESTION	= '\xbf',	/* INVERTED QUESTION MARK */
	UCASE_A_GRAVE	= '\xc0',	/* LATIN CAPITAL LETTER A WITH GRAVE */
	UCASE_A_ACUTE	= '\xc1',	/* LATIN CAPITAL LETTER A WITH ACUTE */
	UCASE_A_CIRCUM	= '\xc2',	/* LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
	UCASE_A_TILDE	= '\xc3',	/* LATIN CAPITAL LETTER A WITH TILDE */
	UCASE_A_DIAERES = '\xc4',	/* LATIN CAPITAL LETTER A WITH DIAERESIS */
	UCASE_A_RINGA	= '\xc5',	/* LATIN CAPITAL LETTER A WITH RING ABOVE */
	UCASE_AE	= '\xc6',	/* LATIN CAPITAL LETTER AE */
	UCASE_C_CEDILLA = '\xc7',	/* LATIN CAPITAL LETTER C WITH CEDILLA */
	UCASE_E_GRAVE	= '\xc8',	/* LATIN CAPITAL LETTER E WITH GRAVE */
	UCASE_E_ACUTE	= '\xc9',	/* LATIN CAPITAL LETTER E WITH ACUTE */
	UCASE_E_CIRCUM	= '\xca',	/* LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
	UCASE_E_DIAERES = '\xcb',	/* LATIN CAPITAL LETTER E WITH DIAERESIS */
	UCASE_I_GRAVE	= '\xcc',	/* LATIN CAPITAL LETTER I WITH GRAVE */
	UCASE_I_ACUTE	= '\xcd',	/* LATIN CAPITAL LETTER I WITH ACUTE */
	UCASE_I_CIRCUM	= '\xce',	/* LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
	UCASE_I_DIAERES = '\xcf',	/* LATIN CAPITAL LETTER I WITH DIAERESIS */
	UCASE_ETH	= '\xd0',	/* LATIN CAPITAL LETTER ETH */
	UCASE_N_TILDE	= '\xd1',	/* LATIN CAPITAL LETTER N WITH TILDE */
	UCASE_O_GRAVE	= '\xd2',	/* LATIN CAPITAL LETTER O WITH GRAVE */
	UCASE_O_ACUTE	= '\xd3',	/* LATIN CAPITAL LETTER O WITH ACUTE */
	UCASE_O_CIRCUM	= '\xd4',	/* LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
	UCASE_O_TILDE	= '\xd5',	/* LATIN CAPITAL LETTER O WITH TILDE */
	UCASE_O_DIAERES = '\xd6',	/* LATIN CAPITAL LETTER O WITH DIAERESIS */
	MULT_SIGN	= '\xd7',	/* MULTIPLICATION SIGN */
	UCASE_O_STROKE	= '\xd8',	/* LATIN CAPITAL LETTER O WITH STROKE */
	UCASE_U_GRAVE	= '\xd9',	/* LATIN CAPITAL LETTER U WITH GRAVE */
	UCASE_U_ACUTE	= '\xda',	/* LATIN CAPITAL LETTER U WITH ACUTE */
	UCASE_U_CIRCUM	= '\xdb',	/* LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
	UCASE_U_DIAERES = '\xdc',	/* LATIN CAPITAL LETTER U WITH DIAERESIS */
	UCASE_Y_ACUTE	= '\xdd',	/* LATIN CAPITAL LETTER Y WITH ACUTE */
	UCASE_THORN	= '\xde',	/* LATIN CAPITAL LETTER THORN */
	LCASE_SHARP_S	= '\xdf',	/* LATIN SMALL LETTER SHARP S */
	LCASE_A_GRAVE	= '\xe0',	/* LATIN SMALL LETTER A WITH GRAVE */
	LCASE_A_ACUTE	= '\xe1',	/* LATIN SMALL LETTER A WITH ACUTE */
	LCASE_A_CIRCUM	= '\xe2',	/* LATIN SMALL LETTER A WITH CIRCUMFLEX */
	LCASE_A_TILDE	= '\xe3',	/* LATIN SMALL LETTER A WITH TILDE */
	LCASE_A_DIAERES = '\xe4',	/* LATIN SMALL LETTER A WITH DIAERESIS */
	LCASE_A_RINGA	= '\xe5',	/* LATIN SMALL LETTER A WITH RING ABOVE */
	LCASE_AE	= '\xe6',	/* LATIN SMALL LETTER AE */
	LCASE_C_CEDILLA = '\xe7',	/* LATIN SMALL LETTER C WITH CEDILLA */
	LCASE_E_GRAVE	= '\xe8',	/* LATIN SMALL LETTER E WITH GRAVE */
	LCASE_E_ACUTE	= '\xe9',	/* LATIN SMALL LETTER E WITH ACUTE */
	LCASE_E_CIRCUM	= '\xea',	/* LATIN SMALL LETTER E WITH CIRCUMFLEX */
	LCASE_E_DIAERES = '\xeb',	/* LATIN SMALL LETTER E WITH DIAERESIS */
	LCASE_I_GRAVE	= '\xec',	/* LATIN SMALL LETTER I WITH GRAVE */
	LCASE_I_ACUTE	= '\xed',	/* LATIN SMALL LETTER I WITH ACUTE */
	LCASE_I_CIRCUM	= '\xee',	/* LATIN SMALL LETTER I WITH CIRCUMFLEX */
	LCASE_I_DIAERES = '\xef',	/* LATIN SMALL LETTER I WITH DIAERESIS */
	LCASE_ETH	= '\xf0',	/* LATIN SMALL LETTER ETH */
	LCASE_N_TILDE	= '\xf1',	/* LATIN SMALL LETTER N WITH TILDE */
	LCASE_O_GRAVE	= '\xf2',	/* LATIN SMALL LETTER O WITH GRAVE */
	LCASE_O_ACUTE	= '\xf3',	/* LATIN SMALL LETTER O WITH ACUTE */
	LCASE_O_CIRCUM	= '\xf4',	/* LATIN SMALL LETTER O WITH CIRCUMFLEX */
	LCASE_O_TILDE	= '\xf5',	/* LATIN SMALL LETTER O WITH TILDE */
	LCASE_O_DIAERES = '\xf6',	/* LATIN SMALL LETTER O WITH DIAERESIS */
	DIVISION_SIGN	= '\xf7',	/* DIVISION SIGN */
	LCASE_O_STROKE	= '\xf8',	/* LATIN SMALL LETTER O WITH STROKE */
	LCASE_U_GRAVE	= '\xf9',	/* LATIN SMALL LETTER U WITH GRAVE */
	LCASE_U_ACUTE	= '\xfa',	/* LATIN SMALL LETTER U WITH ACUTE */
	LCASE_U_CIRCUM	= '\xfb',	/* LATIN SMALL LETTER U WITH CIRCUMFLEX */
	LCASE_U_DIAERES = '\xfc',	/* LATIN SMALL LETTER U WITH DIAERESIS */
	LCASE_Y_ACUTE	= '\xfd',	/* LATIN SMALL LETTER Y WITH ACUTE */
	LCASE_THORN	= '\xfe',	/* LATIN SMALL LETTER THORN */
	LCASE_Y_DIAERES = '\xff',	/* LATIN SMALL LETTER Y WITH DIAERESIS */
} ascii_t;
